
[package]
name = "shitlang"
version = "0.0.∞"
edition = "2021"

[dependencies]


[features]
default = ["give_up"]
give_up = []
broken_macro = []
entropy_runtime = []
unfeature_nightmare = []
compat_windows_95 = []